database:
  # Type can be MYSQL, MARIADB, or SQLITE
  type: "SQLITE"
  mysql:
    host: "127.0.0.1"
    port: 3306
    name: "arqoland"
    username: "root"
    password: ""
  sqlite:
    file-name: "database.db"
  pool-size: 10

limits:
  default-max-lands: 1
  default-max-members: 5
  max-claim-size: 25

taxes:
  enabled: true
  grace-period-days: 7
  diamond-cost-per-week: 70

discord-webhook:
  enabled: false
  url: "https://discord.com/api/webhooks/xxxx/xxxx"
  embed-color: "#FF0000"

visuals:
  border-particles: true
  welcome-title-enabled: true
  default-greeting: "&eSelamat Datang di {land_name}"
  hologram-duration-seconds: 5
  hologram-view-distance: 20

upgrades:
  perks:
    level-1: 64
    level-2: 128
    level-3: 256
    level-4: 512
    level-5: 1024
  heart:
    level-1: 500
    level-2: 1000
    level-3: 2000
    level-4: 2500
    level-5: 4000
    level-6: 5000
  turret:
    level-1: 2000
    level-2: 4000
    level-3: 8000
    level-4: 15000
    level-5: 30000
    infinity-ammo: 7000

turrets:
  range-base: 16
  range-per-level: 12
  base-damage: 4.0
  max-turrets-per-land: 5
