name: ArqoLand
version: '${project.version}'
main: dev.arqo.land.ArqoLand
api-version: '1.20'
folia-supported: true
authors: [Dzakiri]
description: Enterprise Land Claiming System for Folia
softdepend: [PlaceholderAPI]

commands:
  arqoland:
    description: Perintah utama ArqoLand
    aliases: [al, land]
    usage: /al help
